### ISSUE TITLE
頁面不會滑動

### ISSUE THREAD

**Issue by tarawei** [tarawei/quantumMedia#3]
原本的會滑動，但增加pagepiling menu的用法是因為原本的方式遇到一些問題：
我的kv首頁和about被當作是同一頁，所以當我點到about的時候我的kv首頁還是會擋在前面
所以想說是否用pagepiling menu的方式寫不知的會不會調整好，加了之後雖然點了個按鈕網址後面會連到＃該頁面
但是畫面不會滑動了...

**Comment by sexyoung** [comment]
在這邊解掉了
https://github.com/tarawei/quantumMedia/commit/31751dbb1fe351d043df4178ee5fdbb19572e0fa
